# Generated by Django 4.0.5 on 2022-06-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_clogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='uregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('mp', models.CharField(max_length=200)),
                ('ward', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='clogin',
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
