# Generated by Django 4.0.5 on 2022-06-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_uregister_delete_clogin_delete_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='uregister',
            new_name='ureg',
        ),
    ]
