# Generated by Django 4.0.5 on 2022-06-20 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_gov'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gov',
        ),
    ]
