# Generated by Django 4.0.5 on 2022-06-20 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_gov'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creg',
            name='mp',
        ),
    ]
