# Generated by Django 4.0.5 on 2022-07-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_newproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('expenditure', models.CharField(max_length=200)),
            ],
        ),
    ]
