# Generated by Django 4.0.5 on 2022-07-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_expenditure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenditure',
            old_name='expenditure',
            new_name='exp',
        ),
    ]
