# Generated by Django 3.2.13 on 2022-09-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_expenditure_expenditure_exp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ngoreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('mob', models.CharField(max_length=200)),
                ('ward', models.CharField(max_length=200)),
            ],
        ),
    ]
