# Generated by Django 3.2.13 on 2022-09-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_ngoreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
