# Generated by Django 4.1 on 2023-01-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_expenditure_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ureg',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
