# Generated by Django 3.2.13 on 2023-04-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_ureg_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ureg',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
